apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: selenium-grid-qa-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/SiddharthGupta25/container-pipeline-tools.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: selenium-qa

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true